### ISSUE TITLE
Massive pyrobot develop <=> master merge needed

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/pyrobotlab#77]
a massive merge between the two repo's is needed - we "now" support develop & master references in blogs & Service Pages.

In theory, development is done on development and merged into master when there is a release.  I understand many people creating scripts and adding content do not understand this .. and for the most part its ok.  

Many people only work on master and that is ok, because "usually" the same people work only with released versions of mrl (this will be future)

Those people interested in writing scripts against develop branch may need to change their scripts drastically, and they often won't work with the released version. 

These 2 branches keeps things stable, but people need to play by the rules.

In the future, if you want to play with bleeding-edge "develop" myrobotlab - you should be using the "develop" branch in pyrobotlab !

This ticket is to resolve differences between the two branches - as we come near to an actual release - develop & master branch will momentarily become the same.  This merge ticket is to "make them the same"

**Comment by supertick** [comment]
Alright planning to merge develop into master - let me know if anyone has any concerns, or suggestions .. or wishes of good luck ..

The exact plan is - first merge master into develop ... resolve conflicts - (repeat if necessary) ... then merge develop into master

git checkout develop
git merge master
... resolve conflicts ..  repeat  .. git pull, git merge master .. resolve conflicts
git checkout master
git merge develop

at least that's the current plan ...

**Comment by kwatters** [comment]
sounds like a good plan.  in reality, you could probably just cherry pick the commits from develop onto master.. that might be easier if there aren't a lot of commits to develop.

**Comment by supertick** [comment]
merged master into develop
resolved conflicts (as best i could)
pushed develop
merged develop into master
pushed master

We are in sync ! 

Now I will begin working on creating & testing service files ! 
These are great to have as examples.

I would want the ability to 
got to a Service page - find an example - and run and watch it be worky !
(creating new ticket for pyrobotlab /service/ files help)

**Comment by supertick** [comment]
All new develop "now" will be done on develop branch
The documents now allow you to switch - if your working with "develop" branch please check in corresponding pyrobotlab "develop" python files !
